CREATE TABLE EVENTS (
    ID int NOT NULL,
    EVENTTIME timestamp NOT NULL default now(),
    CONSTRAINT ID PRIMARY KEY (ID)
);

CREATE TABLE EXTERNS (
    CIP1 varchar(8) NOT NULL,
    CIP2 varchar(8) NOT NULL,
    EXTERN_NAME text NOT NULL,
    EVENT_ID int NOT NULL,
    CONSTRAINT EXTERN_PK PRIMARY KEY (CIP1,CIP2,EXTERN_NAME,EVENT_ID),
    CONSTRAINT ID_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENTS (ID)
);
