CREATE TABLE EVENTS (
    ID int NOT NULL,
    EVENTTIME timestamp NOT NULL default now(),
    CONSTRAINT EVENTS_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE USERS (
    CIP varchar(8) NOT NULL,
    FIRSTNAME text NOT NULL,
    LASTNAME text NOT NULL,
    CONSTRAINT USERS_CIP_PK PRIMARY KEY (CIP)
);

CREATE TABLE EXTERNS (
    CIP1 varchar(8) NOT NULL,
    CIP2 varchar(8) NOT NULL,
    EXTERN_NAME text NOT NULL,
    EVENT_ID int NOT NULL,
    CONSTRAINT EXTERNS_PK PRIMARY KEY (CIP1,CIP2,EXTERN_NAME,EVENT_ID),
    CONSTRAINT EXTERNS_ID_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENTS (ID),
    CONSTRAINT EXTERNS_CIP1_FK FOREIGN KEY (CIP1) REFERENCES USERS (CIP),
    CONSTRAINT EXTERNS_CIP2_FK FOREIGN KEY (CIP2) REFERENCES USERS (CIP)
);